### ISSUE TITLE
Vehicle Assets

### ISSUE THREAD

**Issue by Jsayer7** [pubg/api-assets#10]
The included assets are awesome, great job! However, I noticed that there are no assets provided for vehicles. It would be great if vehicle assets could get included as well.

**Comment by jaloisi834** [comment]
I agree. I'll see what we can do.

**Comment by jaloisi834** [comment]
Most of the vehicles are ready to be added. We are just working on getting a few more. You can see our progress in PR #17.

**Comment by jaloisi834** [comment]
All set. =)
