### ISSUE TITLE
Weapon Images: Apple / BigBomb

### ISSUE THREAD

**Issue by kfitzgerald** [pubg/api-assets#11]
These seem to be unreferenced. Perhaps left overs from dev or placeholders?

https://github.com/pubg/api-assets/blob/master/assets/weapons/Item_Weapon_Apple.png
https://github.com/pubg/api-assets/blob/master/assets/weapons/Item_Weapon_BigBomb.png

Thanks,
-Kevin

**Comment by andrewbroberg** [comment]
I want to throw an apple at my enemies!

**Comment by jaloisi834** [comment]
Yeah. They are just extras. I'll be removing them as part of a different update soon.
