### ISSUE TITLE
Missing dictionary telemetry on damageCauserName.json

### ISSUE THREAD

**Issue by riquemuramoto** [pubg/api-assets#112]
Hi,

Just for notice, not exactly an issue.

Looking the telemetry data from recent matches and the data of the damageCauserName for the melee throw kill, i get the data "WeapSickleProjectile_C" for the damageCauserName.
This data is not on the json file on 'api-assets/dictionaries/telemetry/damageCauserName.json'.
I believe there are missing for each melee weapon too.

**Comment by matizm** [comment]
Thank you! This is fixed with [#115](https://github.com/pubg/api-assets/pull/115)
