### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by alangregory** [pubg/api-assets#13]
Some missing assets:

"Item_Ghillie_01_C": "Ghillie Suit",
"Item_Ghillie_02_C": "Ghillie Suit",
"Item_Attach_Weapon_Lower_QuickDraw_Large_Crossbow_C": "QuickDraw Crossbow Quiver",

**Comment by alangregory** [comment]
In addition, items from the last update are missing.

**Comment by jaloisi834** [comment]
Thanks for the heads up. Moving these to issue #12 to keep things in one place.
