### ISSUE TITLE
Map icons

### ISSUE THREAD

**Issue by RafaelKayumov** [pubg/api-assets#16]
Would be good to have map icons images from PC game client included.
Thanks.

![mapiconsscheme](https://user-images.githubusercontent.com/1227859/40446842-3ffb297e-5ed9-11e8-9d48-87b723bfe965.png)

**Comment by jaloisi834** [comment]
We have these ready to go in PR #17. Just finishing up a few things and we will have them merged.

**Comment by jaloisi834** [comment]
All set. =)
