### ISSUE TITLE
Need survival level icons.

### ISSUE THREAD

**Issue by ultravires** [pubg/api-assets#261]
![image](https://github.com/pubg/api-assets/assets/26894991/3a1ebfec-b06b-4702-8364-e64cf7e75003)

**Comment by ultravires** [comment]
Need TIER Icons. Thanks.  https://pubg.sanphantom.com

**Comment by vpcks9** [comment]
من انتم


في الأحد، ٤ فبراير، ٢٠٢٤, ١١:٤٦ ص ultravires ***@***.***> كتب:
