### ISSUE TITLE
Miramar map update

### ISSUE THREAD

**Issue by IkeKap** [pubg/api-assets#4]
Thank you very much for putting this repo into the wild. 

According to [this](https://steamcommunity.com/games/578080/announcements/detail/1651007810318992139) it seems that the map Mirarmar is getting substantial changes. Would it be possible for the map image in this repo to be updated in the near future to reflect the new changes?

Thank you very much in advance for your consideration

**Comment by jaloisi834** [comment]
The Miramar map asset has been updated.
