### ISSUE TITLE
Vikendi Map Icon

### ISSUE THREAD

**Issue by tymelx** [pubg/api-assets#49]
Could we get the icon added for the Vikendi map? Am guessing it will either be a snowflake or a snowman?

**Comment by tsupertramp** [comment]
![dihorotok_main](https://user-images.githubusercontent.com/8327755/50530345-d601f680-0afc-11e9-9851-e4ab775b8011.png)

I made myself something till something official is released. Not pretty but maybe someone else wants to use it. Publishing my "great 10 second artwork" under https://choosealicense.com/licenses/unlicense/
