### ISSUE TITLE
Missing item image assets

### ISSUE THREAD

**Issue by jhartikainen** [pubg/api-assets#5]
At least the following image assets appear to be missing:

- ~Item_Head_G_01_Lv3_C~
- ~Item_Heal_MedKit_C~
- ~Item_Heal_Bandage_C~
- ~Item_Heal_FirstAid_C~
- ~Item_Boost_EnergyDrink_C~
- ~Item_JerryCan_C~
- ~Item_Head_F_01_Lv2_C~
- ~Item_Weapon_Sawnoff_C~
- ~Item_Head_F_02_Lv2_C~
- ~Item_Head_E_02_Lv1_C~
- ~Item_Head_E_01_Lv1_C~
- ~Item_Weapon_Rhino_C~
- ~Item_Weapon_Win1894_C~
- ~Item_Weapon_AUG_C~
- Item_Attach_Weapon_Upper_ACOG_01 (The file exists, but is currently showing the 2X scope)

**Comment by jhartikainen** [comment]
Added another missing item:

- Item_Weapon_AUG_C

**Comment by gintsmurans** [comment]
@jaloisi834 Its great that you guys are making all these assets available for others to use. Thanks.

As for assets, Flare gun is also missing. It would also be nice to have default gloves image available.

**Comment by gintsmurans** [comment]
Newly added weapons is in different format - looks more cartoonish than the rest of them and is also named icon_* not item_*, so I am guessing those are not final images. Yup - 4x have wrong image.

**Comment by jhartikainen** [comment]
Looks like the 4x scope has been added and the images which were a bit different from the others have also been replaced.

Closing this since as far as I can tell all the common images exist now

**Comment by gintsmurans** [comment]
4x Scope is ok, but from weapons it seems that only Winchester1894.png is added, rest of the missing ones are icons.

**Comment by jaloisi834** [comment]
Unfortunately, those icon images for those missing ones were the best we could get for now. We will try to get the full size images when possible.
