### ISSUE TITLE
Missing License to use Assets

### ISSUE THREAD

**Issue by iv-mexx** [pubg/api-assets#6]
As far as I can see, the [API TOS](https://developer.playbattlegrounds.com/tos?locale=en) do not mention anything about the assets. There needs to be some license to allow the use of the assets.

**Comment by jaloisi834** [comment]
Sorry for not saying anything sooner. We are working on this.

**Comment by jaloisi834** [comment]
Sorry about the delay. I have been informed that the use of assets is covered under the "© 2018 PUBG Corporation. All rights reserved." footer on the developer portal.
