### ISSUE TITLE
Text-free asset of Miramar map is outdated

### ISSUE THREAD

**Issue by JoelBesada** [pubg/api-assets#60]
Comparing the following assets:
* https://github.com/pubg/api-assets/blob/master/Assets/Maps/Miramar_Main_Low_Res.jpg  and
* https://github.com/pubg/api-assets/blob/master/Assets/Maps/Miramar_Main_No_Text_Low_Res.jpg

You'll see that the text-free version of the map lacks a bunch of the buildings that have been added in a later update. An updated version of the no text variant would be very much appreciated!

**Comment by matizm** [comment]
@JoelBesada I'm happy to look for something more recent, but would you mind clarifying where you see buildings lacking so that I can confirm the new version has them?

**Comment by JoelBesada** [comment]
@matizm 

![image](https://user-images.githubusercontent.com/688415/52364982-acff4a80-2a46-11e9-9bda-2de135bb4872.png)

I've marked some of the areas (there are a lot more) in the up-to-date text version that have missing buildings in the text-free version. Most notably missing is the extended areas of water at the north of the map. 

For reference, here are the same areas marked on the outdated version: 
![image](https://user-images.githubusercontent.com/688415/52365253-5e05e500-2a47-11e9-9704-ec80376d2b2d.png)

**Comment by matizm** [comment]
@JoelBesada Thank you very much for taking the time to do that. The new version of the map has been uploaded :-)
