### ISSUE TITLE
Asset Name Convention

### ISSUE THREAD

**Issue by Livijn** [pubg/api-assets#8]
The naming of the asset files is not the same as the ones provided by the Telemetry JSON API. I did notice that most item assets are retrievable by removing the last `_` and remaining contents. However, some items are named `icon_` which is really confusing, and the *AUG* is named `Item_Weapon_AUGA3.png` while the *itemId* is `Item_Weapon_AUG_C`.

I would like some more consistency to the naming of the files. I suppose I will have to manually rename those with irregularities for now.

**Comment by jhartikainen** [comment]
I think the Item_ prefixed filenames were added for AUG and Win94 which were the two ones with wrong images?

Besides that - there are a lot of exceptions unfortunately in the image naming scheme vs. item ID values.

**Comment by jaloisi834** [comment]
Thanks for the call out. I'll work on fixing the names of the image files to match today.

**Comment by jhartikainen** [comment]
Looks good to me. Seems to correct the item images at least.

The other things that are a bit off are the HUD icons, primarily in the item ID -> filename mapping as well.

I think I'm going to have to update my database schema to store item types as well in addition to just the item ID so the images for them can be selected easily now that they have a nicer organization :)

**Comment by alangregory** [comment]
@jaloisi834  Is Item_ missing in front of armor/head/backpacks names or is it intended ?

**Comment by jaloisi834** [comment]
No, that's my bad. I'll fix that shortly. =)

**Comment by jaloisi834** [comment]
Icons have been renamed/reorganized, and the vest/backpack naming is fixed.
