### ISSUE TITLE
Vikendi map: houses missing

### ISSUE THREAD

**Issue by Luroleverell** [pubg/api-assets#83]
![image](https://user-images.githubusercontent.com/38363936/58880800-0fa4e200-86d9-11e9-92fe-43e916b5367b.png)

There seems to be missing a few houses south of sawmill far to south west on Vikendi. Streight south for the 'w' in sawmill there should be a couple of houses.

**Comment by XuluniX** [comment]
The minimap images for Sanhok and Vikendi have been updated but the no-text versions are still outdated

**Comment by matizm** [comment]
Thanks for letting us know. The maps have been updated.
